### ISSUE TITLE
Item-paywall don't take away the item

### ISSUE THREAD

**Issue by MarkGG8181** [rockyhawk64/CommandPanels#203] opened 2022-05-18 16:57 UTC
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
Yes

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
Yes

### Describe the bug
When using the command item-paywall= WOOL 64 it doesn't take away the wool, it just continues with the next command if you have enough wool. It works with every single item not just wool. It doesn't give any error, it just continues with the next command after they paywall if you have the item.

### To Reproduce
1. Make a panel with a item
2. Add commands: item-paywall= wool 64 and console= kit sheep %cp-player-name%
3. click item with 64 wool in inventory
4. Chat shows sold wool but doesn't take away the wool and continues on giving the kit

### Expected behavior
I expected to sell the wool block and get my kit

### Screenshots/videos
If applicable, add screenshots or videos to help explain your problem.
Video of what happens: [https://streamable.com/4hqyy9](https://streamable.com/4hqyy9)
[screenshot of no error](https://cdn.discordapp.com/attachments/749407995036696656/976179125926629376/unknown.png)

### Versions:
 - Minecraft: 1.8.8 / Paper Server
 - CommandPanels: 3.17.4.3 (latest right now)

### Additional context/Panel files
Add any other context or about the problem here. Please also send you're panel in question. We only accept [pastebin](https://pastebin.com/) links.
https://pastebin.com/ifcT5hYT

**Comment by jman13378** [comment] 2022-05-18 17:00
So because your using a Version below 1.12 you might need to add an ID to the paywall

**Comment by BooIMDD** [comment] 2022-05-18 17:01
> So because your using a Version below 1.12 you might need to add an ID to the paywall

already tried, same thing happened

**Comment by jman13378** [comment] 2022-05-18 17:10
Might just be a 1.8 issue might just have to use a has section to check for the wool(i suggest using the papi extension checkitem )them use clear %cp-player-name% wool 64 or whatever the clear cmd is

**Comment by BooIMDD** [comment] 2022-05-18 17:28
> 

the problem is I have tried using has sections but have failed miserably. This also might be a bug and it should be fixed as I can't get the kit shop working

**Comment by jman13378** [comment] 2022-05-18 17:41
It might all be issues with 1.8

**Comment by BooIMDD** [comment] 2022-05-18 17:42
> It might all be issues with 1.8

i have the same issue as [https://github.com/rockyhawk64/CommandPanels/issues/117](https://github.com/rockyhawk64/CommandPanels/issues/117)

**Comment by TinyTank800** [comment] 2024-02-03 05:11
Should be fixed in next pull release from me.

**Closed** 2024-02-03 22:43 UTC
Labels: bug
