### ISSUE TITLE
Middle clicking not working when joining a 1.17.1 server with 1.18/1.18.1

### ISSUE THREAD

**Issue by tyepavitt** [rockyhawk64/CommandPanels#183] opened 2021-12-14 10:35 UTC
### Describe the bug
Middle clicking doesn't work when joining my 1.17.1 server with 1.18/1.18.1.

### To Reproduce
1. Have a 1.17.1 server with command panels, viaversion, viarewind and viabackwards installed
2. Create a panel which has a middle clicking tag (Mine runs a command on middle click)
3. Launch minecraft on 1.18 or 1.18.1
4. Join the 1.17.1 server and try to use the middle clicking

### Expected behavior
Be able to use middle clicking when joining a 1.17.1 server with 1.18/1.18.1.

### Versions:
 - Minecraft: 1.17.1
 - CommandPanels: 3.17.2.1

**Comment by TheLonelyWolf1** [comment] 2021-12-14 16:07
Tried this with an native 1.18.1 Paper Server and it's working as expected.
So this is probably a conflict with the viaversion plugin and not directly caused by CP.

**Comment by rockyhawk64** [comment] 2021-12-21 08:02
Via Version related issue, closing.

**Closed by rockyhawk64** 2021-12-21 08:02 UTC
Labels: bug
