### ISSUE TITLE
Help! .DS_Store file causing errors.

### ISSUE THREAD

**Issue by maxnyman** [rockyhawk64/CommandPanels#9] opened 2020-07-07 08:01 UTC
**Describe the Issue**
I am having an issue. The issue is that in chat it says `Error found in config at: File with no Panels found!` and i also checked if all the YAML was correct.

**Expected behavior**
I expect it to open a GUI menu with 3 options each transporting to a new GUI window.

**Screenshots**
![2020-07-07_14 18 08 copy](https://user-images.githubusercontent.com/242466/86742704-a762c580-c07b-11ea-9eb3-285f97457964.png)

**Versions:**
 - Minecraft: 1.15.2
 - CommandPanels: 3.2.1

**Additional context**
Discord User: Wooferz#6628

**Comment by rockyhawk64** [comment] 2020-07-07 08:11
Can you supply more information as that is a very general error. Sometimes doing /cpd it will give a more specific error in the console.
Also, paste in your panel YML file, and that way I can reproduce or tell you how to fix the issue.

**Comment by fireFerry** [comment] 2020-07-07 08:13
Yeah please copy the panels in here or use pastebin.com

**Comment by maxnyman** [comment] 2020-07-07 08:16
[CommandPanels.zip](https://github.com/rockyhawk64/CommandPanels/files/4883472/CommandPanels.zip)
There are my files

**Comment by fireFerry** [comment] 2020-07-07 08:19
Okay, do you have any console errors? and if you don't see any do /cpd and try again.

**Comment by maxnyman** [comment] 2020-07-07 08:21
This error comes up 
`[17:06:41 ERROR]: Cannot load plugins/CommandPanels/panels/.DS_Store
org.bukkit.configuration.InvalidConfigurationException: unacceptable code point '' (0x0) special characters are not allowed
in "'string'", position 0
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:183) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at me.rockyhawk.commandPanels.premium.commandpanelrefresher.onInventoryOpen(commandpanelrefresher.java:53) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1118) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1104) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.craftbukkit.v1_15_R1.entity.CraftHumanEntity.openCustomInventory(CraftHumanEntity.java:348) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.craftbukkit.v1_15_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:333) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at com.earth2me.essentials.commands.Commandinvsee.run(Commandinvsee.java:32) ~[?:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:161) ~[?:?]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:559) ~[?:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:470) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:723) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1658) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1498) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:211) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:126) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1177) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:287) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:195) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:107) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:141) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:438) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	... 38 more`

**Comment by fireFerry** [comment] 2020-07-07 08:23
there is a file in the panels folder named .DS_Store. Try removing it because it seems that is the issue

**Comment by maxnyman** [comment] 2020-07-07 08:25
.DS_store files are files that you can't remove and if you remove them a new copy will appear because of MacOS

**Comment by fireFerry** [comment] 2020-07-07 08:36
These can be disabled. open up the terminal and execute the following command: `defaults write com.apple.desktopservices DSDontWriteNetworkStores true`. After you reboot the files will no longer be created.

**Comment by rockyhawk64** [comment] 2020-07-07 08:51
I will be fixing this anyways, the DS_Store files also store file preferences for things like icon sizes in certain folders.

**Comment by fireFerry** [comment] 2020-07-07 09:11
This will be closed and once fix is out will be linked with the fix.

**Comment by rockyhawk64** [comment] 2020-07-07 09:49
This has been pushed and a new release is now available:
https://www.spigotmc.org/resources/command-panels-custom-guis.67788/
There should no longer be any issues when the DS_STORE file is there.

**Comment by maxnyman** [comment] 2020-07-07 10:17
ehh...
this showed up in console `[20:00:40 ERROR]: Cannot load plugins/CommandPanels/panels/.DS_Store`
and also i need to go so i wont be able to respond until tomorrow

**Comment by rockyhawk64** [comment] 2020-07-07 10:23
Okay,
could you also supply the rest of the log, that error is not one I have made in CommandPanels so it could for some reason be coming from somewhere else.

**Comment by maxnyman** [comment] 2020-07-07 10:36
[server_log.txt](https://github.com/rockyhawk64/CommandPanels/files/4884229/server_log.txt)

**Comment by fireFerry** [comment] 2020-07-07 10:37
It still seems like it's trying to load it as a panel

**Comment by maxnyman** [comment] 2020-07-07 10:38
Yeah

**Comment by fireFerry** [comment] 2020-07-07 10:38
Will leave this open for @rockyhawk64 to look at.

**Comment by maxnyman** [comment] 2020-07-07 10:39
Ok i will leave for the day

**Comment by fireFerry** [comment] 2020-07-07 12:55
Should be fixed in 3.2.3.

**Closed** 2020-07-09 12:26 UTC
Labels: bug, help wanted
